name: Build and Upload Laook APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Kotlin Lint Repository
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint with Kotlin
        run: ./gradlew lint
      
      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.xml

  build:
    name: Build APK
    needs: lint
    if: ${{ always() && contains(join(needs.lint.result, ','), 'success') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew assembleRelease 

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Laook-APK
          path: app/build/outputs/apk/release/*.apk
